version: '3'

services:
  mysql:
    image: mariadb:10.5.8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: yessql
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./../mysql/init.sql/:/docker-entrypoint-initdb.d/init.sql

  postgres:
      image: postgres
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: yessql
      ports:
        - "5432:5432"
      volumes:
        - ./../postgres/:/docker-entrypoint-initdb.d/
