site_name: yessql
repo_url: https://github.com/mitchelllisle/yessql
repo_name: GitHub
site_author: Mitchell Lisle

theme:
  name: "material"
  features:
    - content.code.annotate

nav:
  - Home: index.md
  - Examples: examples.md
  - API : docs/

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      watch:
        - src/yessql
      handlers:
        python:
          options:
            show_source: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - md_in_html
  - admonition
